### ISSUE TITLE
Adicionar suporte para o Laravel 5.8

### ISSUE THREAD

**Issue by rafatriolo** [stargrid/laravel-calendario-feriados#1]
Ola, boa tarde, tudo bem?

Primeiramente mto obrigado por disponibilizar essa api, acredito que será mto util pra mim. Entretanto eu to usando o laravel 5.8 e no composer.json, vcs dão suporte até o 5.7, vcs podem fazer essa alteração? 

Abs e obrigado.

**Comment by gabrielanhaia** [comment]
@rafatriolo Resolvido no commit https://github.com/stargrid/laravel-calendario-feriados/commit/71324f86c060fdf8ba7f97db26d9a5ee706d682b
Só executar:
`composer require stargrid/laravel-calendario-feriados:"v2.0.0"`
